name: Test

on:
  pull_request:
    paths:
      - "elx/**"
      - "tests/**"
      - "poetry.lock"
      - ".github/workflows/test.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
          cache: "pip"
          cache-dependency-path: "poetry.lock"

      - name: Install Poetry
        run: pip install poetry

      - name: Set Poetry Python version
        run: poetry env use ${{ matrix.python }}

      - name: Install Dependencies
        run: poetry install -E all

      - name: Run test suite
        run: poetry run pytest
